-- PostgreSQL schema equivalent of schema_mysql.sql
-- Note: uses quoted identifiers to preserve original CamelCase names.

CREATE SCHEMA IF NOT EXISTS mydb;

-- Optional: set search_path so you can omit schema prefix in the session
SET search_path TO mydb;

-- -----------------------------------------------------
-- Table mydb."Users"
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS mydb."Users" (
  "idUser"        INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "Firstname"     VARCHAR(45)  NOT NULL,
  "Lastname"      VARCHAR(45)  NOT NULL,
  "Birthdate"     DATE         NOT NULL,
  "Email"         VARCHAR(100) NOT NULL,
  "Phone"         VARCHAR(20)  NOT NULL,
  "Login"         VARCHAR(100) NOT NULL,
  "Password_hash" VARCHAR(255) NOT NULL,
  "Status"        VARCHAR(15)  NOT NULL DEFAULT 'active'
);

CREATE UNIQUE INDEX IF NOT EXISTS "Login_UNIQUE" ON mydb."Users" ("Login");

-- -----------------------------------------------------
-- Table mydb."Sellers"
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS mydb."Sellers" (
  "idSeller"      INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "Name"          VARCHAR(45) NOT NULL,
  "Rating"        SMALLINT    NOT NULL DEFAULT 0,
  "Status"        VARCHAR(15) NOT NULL DEFAULT 'active',
  "Register_Date" DATE        NOT NULL
);

-- -----------------------------------------------------
-- Table mydb."Products"
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS mydb."Products" (
  "idProduct"    INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "Title"        VARCHAR(100) NOT NULL,
  "Seller_id"    INTEGER      NOT NULL,
  "Description"  TEXT         NOT NULL,
  "Price"        NUMERIC(7,2) NOT NULL,
  "Currency"     CHAR(3)      NOT NULL DEFAULT 'EUR',
  "Created_Date" TIMESTAMP    NOT NULL,
  "Quantity"     INTEGER      NOT NULL,
  CONSTRAINT "fk_Products_Seller1"
    FOREIGN KEY ("Seller_id")
    REFERENCES mydb."Sellers" ("idSeller")
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
);

CREATE INDEX IF NOT EXISTS "fk_Products_Seller1_idx" ON mydb."Products" ("Seller_id");

-- -----------------------------------------------------
-- Table mydb."Categories"
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS mydb."Categories" (
  "idCategory" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "Name"       VARCHAR(45) NOT NULL
);

-- -----------------------------------------------------
-- Table mydb."Addresses"
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS mydb."Addresses" (
  "idAddresses" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "Country"     VARCHAR(45) NOT NULL,
  "City"        VARCHAR(45) NOT NULL,
  "Street"      VARCHAR(45) NOT NULL,
  "Appartment"  VARCHAR(10) NOT NULL
);

-- -----------------------------------------------------
-- Table mydb."Orders"
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS mydb."Orders" (
  "idOrder"     INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "Users_id"    INTEGER      NOT NULL,
  "Status"      VARCHAR(15)  NOT NULL DEFAULT 'created',
  "Create_Date" TIMESTAMP    NOT NULL,
  "Paid_Date"   TIMESTAMP    NULL,
  "Price_Total" NUMERIC(7,2) NOT NULL,
  "Currency"    CHAR(3)      NOT NULL DEFAULT 'EUR',
  "Address_id"  INTEGER      NOT NULL,
  CONSTRAINT "fk_Orders_Users1"
    FOREIGN KEY ("Users_id")
    REFERENCES mydb."Users" ("idUser")
    ON UPDATE NO ACTION
    ON DELETE NO ACTION,
  CONSTRAINT "fk_Orders_Addresses1"
    FOREIGN KEY ("Address_id")
    REFERENCES mydb."Addresses" ("idAddresses")
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
);

CREATE INDEX IF NOT EXISTS "fk_Orders_Users1_idx" ON mydb."Orders" ("Users_id");
CREATE INDEX IF NOT EXISTS "fk_Orders_Addresses1_idx" ON mydb."Orders" ("Address_id");

-- -----------------------------------------------------
-- Table mydb."Product_Categories"
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS mydb."Product_Categories" (
  "Product_id"  INTEGER NOT NULL,
  "Category_id" INTEGER NOT NULL,
  PRIMARY KEY ("Product_id", "Category_id"),
  CONSTRAINT "fk_Products_has_Product_Categories_Products1"
    FOREIGN KEY ("Product_id")
    REFERENCES mydb."Products" ("idProduct")
    ON UPDATE NO ACTION
    ON DELETE NO ACTION,
  CONSTRAINT "fk_Products_has_Product_Categories_Product_Categories1"
    FOREIGN KEY ("Category_id")
    REFERENCES mydb."Categories" ("idCategory")
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
);

CREATE INDEX IF NOT EXISTS "fk_Products_has_Product_Categories_Product_Categories1_idx"
  ON mydb."Product_Categories" ("Category_id");
CREATE INDEX IF NOT EXISTS "fk_Products_has_Product_Categories_Products1_idx"
  ON mydb."Product_Categories" ("Product_id");

-- -----------------------------------------------------
-- Table mydb."Order_Items"
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS mydb."Order_Items" (
  "Order_id"  INTEGER NOT NULL,
  "Product_id" INTEGER NOT NULL,
  "Quantity"  INTEGER NOT NULL,
  PRIMARY KEY ("Order_id", "Product_id"),
  CONSTRAINT "fk_Orders_has_Products_Orders1"
    FOREIGN KEY ("Order_id")
    REFERENCES mydb."Orders" ("idOrder")
    ON UPDATE NO ACTION
    ON DELETE NO ACTION,
  CONSTRAINT "fk_Orders_has_Products_Products1"
    FOREIGN KEY ("Product_id")
    REFERENCES mydb."Products" ("idProduct")
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
);

CREATE INDEX IF NOT EXISTS "fk_Orders_has_Products_Products1_idx"
  ON mydb."Order_Items" ("Product_id");
CREATE INDEX IF NOT EXISTS "fk_Orders_has_Products_Orders1_idx"
  ON mydb."Order_Items" ("Order_id");

-- -----------------------------------------------------
-- Table mydb."User_Addresses"
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS mydb."User_Addresses" (
  "Users_idUser"         INTEGER NOT NULL,
  "Addresses_idAddresses" INTEGER NOT NULL,
  PRIMARY KEY ("Users_idUser", "Addresses_idAddresses"),
  CONSTRAINT "fk_Users_has_Addresses_Users1"
    FOREIGN KEY ("Users_idUser")
    REFERENCES mydb."Users" ("idUser")
    ON UPDATE NO ACTION
    ON DELETE NO ACTION,
  CONSTRAINT "fk_Users_has_Addresses_Addresses1"
    FOREIGN KEY ("Addresses_idAddresses")
    REFERENCES mydb."Addresses" ("idAddresses")
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
);

CREATE INDEX IF NOT EXISTS "fk_Users_has_Addresses_Addresses1_idx"
  ON mydb."User_Addresses" ("Addresses_idAddresses");
CREATE INDEX IF NOT EXISTS "fk_Users_has_Addresses_Users1_idx"
  ON mydb."User_Addresses" ("Users_idUser");